-- MySQL Script generated by MySQL Workbench
-- Sun Jul 18 22:05:49 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema interact-solve
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema interact-solve
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `interact-solve` DEFAULT CHARACTER SET utf8 ;
USE `interact-solve` ;

-- -----------------------------------------------------
-- Table `interact-solve`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `interact-solve`.`questions` (
                                                            `id` INT NOT NULL AUTO_INCREMENT,
                                                            `content` VARCHAR(64) NOT NULL,
                                                            `created_at` DATETIME NOT NULL,
                                                            `updated_at` DATETIME NOT NULL,
                                                            PRIMARY KEY (`id`),
                                                            UNIQUE INDEX `content_UNIQUE` (`content` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `interact-solve`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `interact-solve`.`users` (
                                                        `id` INT NOT NULL AUTO_INCREMENT,
                                                        `name` VARCHAR(64) NOT NULL,
                                                        `mail` VARCHAR(100) NOT NULL,
                                                        `pass` VARCHAR(255) NOT NULL,
                                                        `birthday` DATE NOT NULL,
                                                        `answer` VARCHAR(128) NOT NULL,
                                                        `created_at` DATETIME NOT NULL,
                                                        `updated_at` DATETIME NOT NULL,
                                                        `questions_id` INT NOT NULL,
                                                        PRIMARY KEY (`id`, `questions_id`),
                                                        UNIQUE INDEX `mail_UNIQUE` (`mail` ASC) VISIBLE,
                                                        UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
                                                        INDEX `fk_users_questions1_idx` (`questions_id` ASC) VISIBLE,
                                                        CONSTRAINT `fk_users_questions1`
                                                            FOREIGN KEY (`questions_id`)
                                                                REFERENCES `interact-solve`.`questions` (`id`)
                                                                ON DELETE NO ACTION
                                                                ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `interact-solve`.`consultations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `interact-solve`.`consultations` (
                                                                `id` INT NOT NULL AUTO_INCREMENT,
                                                                `title` VARCHAR(45) NOT NULL,
                                                                `detail` VARCHAR(200) NULL,
                                                                `is_solved` TINYINT NOT NULL,
                                                                `created_at` DATETIME NOT NULL,
                                                                `updated_at` DATETIME NOT NULL,
                                                                `users_id` INT NOT NULL,
                                                                PRIMARY KEY (`id`, `users_id`),
                                                                INDEX `fk_consultation_users_idx` (`users_id` ASC) VISIBLE,
                                                                CONSTRAINT `fk_consultation_users`
                                                                    FOREIGN KEY (`users_id`)
                                                                        REFERENCES `interact-solve`.`users` (`id`)
                                                                        ON DELETE NO ACTION
                                                                        ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `interact-solve`.`replies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `interact-solve`.`replies` (
                                                          `id` INT NOT NULL AUTO_INCREMENT,
                                                          `content` VARCHAR(200) NOT NULL,
                                                          `created_at` DATETIME NOT NULL,
                                                          `updated_at` DATETIME NOT NULL,
                                                          `users_id` INT NOT NULL,
                                                          `consultations_id` INT NOT NULL,
                                                          PRIMARY KEY (`id`, `users_id`, `consultations_id`),
                                                          INDEX `fk_replies_users1_idx` (`users_id` ASC) VISIBLE,
                                                          INDEX `fk_replies_consultations1_idx` (`consultations_id` ASC) VISIBLE,
                                                          CONSTRAINT `fk_replies_users1`
                                                              FOREIGN KEY (`users_id`)
                                                                  REFERENCES `interact-solve`.`users` (`id`)
                                                                  ON DELETE NO ACTION
                                                                  ON UPDATE NO ACTION,
                                                          CONSTRAINT `fk_replies_consultations1`
                                                              FOREIGN KEY (`consultations_id`)
                                                                  REFERENCES `interact-solve`.`consultations` (`id`)
                                                                  ON DELETE NO ACTION
                                                                  ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `interact-solve`.`statuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `interact-solve`.`statuses` (
                                                           `id` INT NOT NULL AUTO_INCREMENT,
                                                           `description` VARCHAR(32) NOT NULL,
                                                           `created_at` DATETIME NOT NULL,
                                                           `updated_at` DATETIME NOT NULL,
                                                           PRIMARY KEY (`id`),
                                                           UNIQUE INDEX `description_UNIQUE` (`description` ASC) VISIBLE,
                                                           UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `interact-solve`.`enters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `interact-solve`.`enters` (
                                                         `id` INT NOT NULL AUTO_INCREMENT,
                                                         `users_id` INT NOT NULL,
                                                         `statuses_id` INT NOT NULL,
                                                         `created_at` DATETIME NOT NULL,
                                                         `updated_at` DATETIME NOT NULL,
                                                         PRIMARY KEY (`id`, `users_id`, `statuses_id`),
                                                         INDEX `fk_actives_statuses1_idx` (`statuses_id` ASC) VISIBLE,
                                                         INDEX `fk_actives_users1_idx` (`users_id` ASC) VISIBLE,
                                                         UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
                                                         UNIQUE INDEX `users_id_UNIQUE` (`users_id` ASC) VISIBLE,
                                                         CONSTRAINT `fk_actives_statuses1`
                                                             FOREIGN KEY (`statuses_id`)
                                                                 REFERENCES `interact-solve`.`statuses` (`id`)
                                                                 ON DELETE NO ACTION
                                                                 ON UPDATE NO ACTION,
                                                         CONSTRAINT `fk_actives_users1`
                                                             FOREIGN KEY (`users_id`)
                                                                 REFERENCES `interact-solve`.`users` (`id`)
                                                                 ON DELETE NO ACTION
                                                                 ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `interact-solve`.`questions`
-- -----------------------------------------------------
START TRANSACTION;
USE `interact-solve`;
INSERT INTO `interact-solve`.`questions` (`id`, `content`, `created_at`, `updated_at`) VALUES (DEFAULT, '生まれた町の名前は？', '2021-07-01 12:00:00', '2021-07-01 12:00:00');
INSERT INTO `interact-solve`.`questions` (`id`, `content`, `created_at`, `updated_at`) VALUES (DEFAULT, '好きなスポーツチームは？', '2021-07-01 12:00:00', '2021-07-01 12:00:00');
INSERT INTO `interact-solve`.`questions` (`id`, `content`, `created_at`, `updated_at`) VALUES (DEFAULT, '子供の頃のニックネームは？', '2021-07-01 12:00:00', '2021-07-01 12:00:00');
INSERT INTO `interact-solve`.`questions` (`id`, `content`, `created_at`, `updated_at`) VALUES (DEFAULT, '初めてのペットの名前は？', '2021-07-01 12:00:00', '2021-07-01 12:00:00');
INSERT INTO `interact-solve`.`questions` (`id`, `content`, `created_at`, `updated_at`) VALUES (DEFAULT, '父親or母親の旧姓は？', '2021-07-01 12:00:00', '2021-07-01 12:00:00');
INSERT INTO `interact-solve`.`questions` (`id`, `content`, `created_at`, `updated_at`) VALUES (DEFAULT, '好きな歌手の名前は？', '2021-07-01 12:00:00', '2021-07-01 12:00:00');

COMMIT;


-- -----------------------------------------------------
-- Data for table `interact-solve`.`statuses`
-- -----------------------------------------------------
START TRANSACTION;
USE `interact-solve`;
INSERT INTO `interact-solve`.`statuses` (`id`, `description`, `created_at`, `updated_at`) VALUES (1, '未手続き', '2021-07-01 00:00:00', '2021-07-01 00:00:00');
INSERT INTO `interact-solve`.`statuses` (`id`, `description`, `created_at`, `updated_at`) VALUES (2, '話しかけてください', '2021-07-01 00:00:00', '2021-07-01 00:00:00');
INSERT INTO `interact-solve`.`statuses` (`id`, `description`, `created_at`, `updated_at`) VALUES (3, '話しかけないでください', '2021-07-01 00:00:00', '2021-07-01 00:00:00');
INSERT INTO `interact-solve`.`statuses` (`id`, `description`, `created_at`, `updated_at`) VALUES (4, 'グループ作業してます', '2021-07-01 00:00:00', '2021-07-01 00:00:00');

COMMIT;

-- -----------------------------------------------------
-- Data for table `interact-solve`.`statuses`
-- -----------------------------------------------------
START TRANSACTION;
USE `interact-solve`;
INSERT INTO `interact-solve`.`users` (`id`, `name`, `mail`, `pass`, `birthday`, `answer`, `created_at`, `updated_at`, `questions_id`) VALUES (1, 'テストユーザー', 'test@example.com', 'test0000', '2000-01-01', '北海道日本ハムファイターズ', '2021-07-01 00:00:00', '2021-07-01 00:00:00', '1');

COMMIT;

